name: CI Pipeline

on: # Runs on every push and pull request
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix: # Defines a matrix for versions
        node-version: [14, 16, 18]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install # Installs dependencies
      - run: npm test # Runs test script
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: path/to/results
        - name: Post-job check # Adds a final step to validate service availability
          run: curl -I <link_to_my_backend.com/health>